# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AI, Machine Learning & more
author: Arthur Colombini Gusmão
author_about: >
  Artificial intelligence researcher.
  Former electrical engineer and web developer.
  Love science and life.
  On a personal quest to crack the matrix.
# email: example@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Articles, book summaries, external links and topics related to Artificial
  Intelligence and Machine Learning.  Also, some other random stuff that I find
  interesting, such as personal development and philosophy about our human
  existence.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  arthurcgusmao
disqus.shortname: arthurcgusmao

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
