# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: arthurcgusmao.com
author: Arthur Colombini Gusmão
author_about: >
  Data Engineer/Scientist living in Zurich, Switzerland.
  Interested in data and software engineering best principles, AI/ML, math, statistics, personal development, mindfulness, communication, and everything related to an active and healthy lifestyle.
# email: example@domain.com
quote: > # this means to ignore newlines until "baseurl:"
  "Through discipline comes freedom." ~ Aristotle

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arthurcgusmao.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: arthurcgusmao
disqus:
  shortname: arthurcgusmao

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
